added a lot of cool aestics, but mostly placed my city weather sections in seperate divs so that I would be able to manipulate them with the new dragNdrop, but able to due to error Uncaught TypeError cObj.childNodesj.setAttribute is not a function